title: Yujia Gao
url: "https://jenniferry0701.github.io/personal-website"
baseurl: "/personal-website"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_text: "Last updated on 02/21/25"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Contact"
   link: "contact"
 - name: "About"
   link: "/personal-website"
 - name: "CV"
   link: "CV.pdf"

